DROP TABLE IF EXISTS barangays;
CREATE TABLE IF NOT EXISTS barangays (
  brgy_id int(11) NOT NULL,
  barangay varchar(50) DEFAULT NULL,
  municipality varchar(50) DEFAULT NULL,
  PRIMARY KEY (brgy_id)
);

INSERT INTO `barangays` (`brgy_id`, `barangay`, `municipality`) VALUES
(1,  'Acad',               'Aurora'),
(2,  'Alang-Alang',        'Aurora'),
(3,  'Alegria',            'Aurora'),
(4,  'Anonang',            'Aurora'),
(5,  'Bagong Mandaue',     'Aurora'),
(6,  'Bagong Maslog',      'Aurora'),
(7,  'Bagong Oslob',       'Aurora'),
(8,  'Bagong Pitogo',      'Aurora'),
(9,  'Baki',               'Aurora'),
(10, 'Balas',              'Aurora'),
(11, 'Balide',             'Aurora'),
(12, 'Balintawak',         'Aurora'),
(13, 'Bayabas',            'Aurora'),
(14, 'Bemposa',            'Aurora'),
(15, 'Cabilinan',          'Aurora'),
(16, 'Campo Uno',          'Aurora'),
(17, 'Ceboneg',            'Aurora'),
(18, 'Commonwealth',       'Aurora'),
(19, 'Gubaan',             'Aurora'),
(20, 'Inasagan',           'Aurora'),
(21, 'Inroad',             'Aurora'),
(22, 'Kahayagan East',     'Aurora'),
(23, 'Kahayagan West',     'Aurora'),
(24, 'Kauswagan',          'Aurora'),
(25, 'La Paz',             'Aurora'),
(26, 'La Victoria',        'Aurora'),
(27, 'Lantungan',          'Aurora'),
(28, 'Libertad',           'Aurora'),
(29, 'Lintugop',           'Aurora'),
(30, 'Lubid',              'Aurora'),
(31, 'Maguikay',           'Aurora'),
(32, 'Mahayahay',          'Aurora'),
(33, 'Monte Alegre',       'Aurora'),
(34, 'Montela',            'Aurora'),
(35, 'Napo',               'Aurora'),
(36, 'Panaghiusa',         'Aurora'),
(37, 'Poblacion',          'Aurora'),
(38, 'Resthouse',          'Aurora'),
(39, 'Romarate',           'Aurora'),
(40, 'San Jose',           'Aurora'),
(41, 'San Juan',           'Aurora'),
(42, 'Sapa Loboc',         'Aurora'),
(43, 'Tagulalo',           'Aurora'),
(44, 'Waterfall',          'Aurora'),
(45, 'Baking',             'Bayog'),
(46, 'Balukbahan',         'Bayog'),
(47, 'Balumbunan',         'Bayog'),
(48, 'Bantal',             'Bayog'),
(49, 'Bobuan',             'Bayog'),
(50, 'Camp Blessing',      'Bayog'),
(51, 'Canoayan',           'Bayog'),
(52, 'Conacon',            'Bayog'),
(53, 'Dagum',              'Bayog'),
(54, 'Damit',              'Bayog'),
(55, 'Datagan',            'Bayog'),
(56, 'Depase',             'Bayog'),
(57, 'Depili',             'Bayog'),
(58, 'Depore',             'Bayog'),
(59, 'Deporehan',          'Bayog'),
(60, 'Dimalinao',          'Bayog'),
(61, 'Kahayagan',          'Bayog'),
(62, 'Kanipaan',           'Bayog'),
(63, 'Lamare',             'Bayog'),
(64, 'Liba',               'Bayog'),
(65, 'Matin-ao',           'Bayog'),
(66, 'Matun-og',           'Bayog'),
(67, 'San Isidro',         'Bayog'),
(68, 'Poblacion',          'Bayog'),
(69, 'Pulang Bato',        'Bayog'),
(70, 'Salawagan',          'Bayog'),
(71, 'Sigacad',            'Bayog'),
(72, 'Supon',              'Bayog'),
(73, 'Bacayawan',          'Dimataling'),
(74, 'Baha',               'Dimataling'),
(75, 'Balanagan',          'Dimataling'),
(76, 'Baluno',             'Dimataling'),
(77, 'Binuay',             'Dimataling'),
(78, 'Buburay',            'Dimataling'),
(79, 'Grap',               'Dimataling'),
(80, 'Josefina',           'Dimataling'),
(81, 'Kagawasan',          'Dimataling'),
(82, 'Lalab',              'Dimataling'),
(83, 'Libertad',           'Dimataling'),
(84, 'Magahis',            'Dimataling'),
(85, 'Mahayag',            'Dimataling'),
(86, 'Mercedes',           'Dimataling'),
(87, 'Poblacion',          'Dimataling'),
(88, 'Saloagan',           'Dimataling'),
(89, 'San Roque',          'Dimataling'),
(90, 'Sugbay Uno',         'Dimataling'),
(91, 'Sumbato',            'Dimataling'),
(92, 'Sumpot',             'Dimataling'),
(93, 'Tinggabulong',       'Dimataling'),
(94, 'Tiniguangan',        'Dimataling'),
(95, 'Tipangi',            'Dimataling'),
(96, 'Upper Ludiong',      'Dimataling'),
(97, 'Bacawan',            'Dinas'),
(98, 'Benuatan',           'Dinas'),
(99, 'Beray',              'Dinas'),
(100, 'Don Jose',          'Dinas'),
(101, 'Dongos',            'Dinas'),
(102, 'East Migpulao',     'Dinas'),
(103, 'Guinicolalay',      'Dinas'),
(104, 'Ignacio Garrata',   'Dinas'),
(105, 'Kinakap',           'Dinas'),
(106, 'Legarda 1',         'Dinas'),
(107, 'Legarda 2',         'Dinas'),
(108, 'Legarda 3',         'Dinas'),
(109, 'Lower Dimaya',      'Dinas'),
(110, 'Locuban',           'Dinas'),
(111, 'Ludiong',           'Dinas'),
(112, 'Nangka',            'Dinas'),
(113, 'Nian',              'Dinas'),
(114, 'Old Mirapao',       'Dinas'),
(115, 'Pisa-an',           'Dinas'),
(116, 'Poblacion',         'Dinas'),
(117, 'Proper Dimaya',     'Dinas'),
(118, 'Sagacad',           'Dinas'),
(119, 'Sambulawan',        'Dinas'),
(120, 'San Isidro',        'Dinas'),
(121, 'Songayan',          'Dinas'),
(122, 'Sumpotan',          'Dinas'),
(123, 'Tarakan',           'Dinas'),
(124, 'Upper Dimaya',      'Dinas'),
(125, 'Upper Sibul',       'Dinas'),
(126, 'West Migpulao',     'Dinas'),
(127, 'Anonang',           'Dumalinao'),
(128, 'Baga',              'Dumalinao'),
(129, 'Bag-ong Misamis',   'Dumalinao'),
(130, 'Bag-ong Silao',     'Dumalinao'),
(131, 'Baloboan',          'Dumalinao'),
(132, 'Banta-ao',          'Dumalinao'),
(133, 'Bibilik',           'Dumalinao'),
(134, 'Calingayan',        'Dumalinao'),
(135, 'Camalig',           'Dumalinao'),
(136, 'Camanga',           'Dumalinao'),
(137, 'Cuatro-cuatro',     'Dumalinao'),
(138, 'Locuban',           'Dumalinao'),
(139, 'Malasik',           'Dumalinao'),
(140, 'Mama (San Juan)',   'Dumalinao'),
(141, 'Matab-ang',         'Dumalinao'),
(142, 'Mecolong',          'Dumalinao'),
(143, 'Metokong',          'Dumalinao'),
(144, 'Motosawa',          'Dumalinao'),
(145, 'Pag-asa (Pob)',     'Dumalinao'),
(146, 'Paglaum (Pob)',     'Dumalinao'),
(147, 'Pantad',            'Dumalinao'),
(148, 'Piniglibano',       'Dumalinao'),
(149, 'Rebokon',           'Dumalinao'),
(150, 'San Agustin',       'Dumalinao'),
(151, 'Sebucao',           'Dumalinao'),
(152, 'Sumadat',           'Dumalinao'),
(153, 'Tikwas',            'Dumalinao'),
(154, 'Tina',              'Dumalinao'),
(155, 'Tubo-Pait',         'Dumalinao'),
(156, 'Upper Dumalinao',   'Dumalinao'),
(157, 'Bag-ong Kauswagan', 'Dumingag'),
(158, 'Bag-ong Silangan',  'Dumingag'),
(159, 'Bag-ong Valencia',  'Dumingag'),
(160, 'Bucayan',           'Dumingag'),
(161, 'Calumanggi',        'Dumingag'),
(162, 'Canibongan',        'Dumingag'),
(163, 'Caridad',           'Dumingag'),
(164, 'Danlugan',          'Dumingag'),
(165, 'Dapiwak',           'Dumingag'),
(166, 'Datu Totocan',      'Dumingag'),
(167, 'Dilud',             'Dumingag'),
(168, 'Ditulan',           'Dumingag'),
(169, 'Dulian',            'Dumingag'),
(170, 'Dulop',             'Dumingag'),
(171, 'Guintananan',       'Dumingag'),
(172, 'Guitran',           'Dumingag'),
(173, 'Gumpingan',         'Dumingag'),
(174, 'La Fortuna',        'Dumingag'),
(175, 'Labangon',          'Dumingag'),
(176, 'Libertad',          'Dumingag'),
(177, 'Licabang',          'Dumingag'),
(178, 'Lipawan',           'Dumingag'),
(179, 'Lower Landing',     'Dumingag'),
(180, 'Lower Timonan',     'Dumingag'),
(181, 'Macasing',          'Dumingag'),
(182, 'Mahayahay',         'Dumingag'),
(183, 'Malagalad',         'Dumingag'),
(184, 'Manlabay',          'Dumingag'),
(185, 'Maralag',           'Dumingag'),
(186, 'Marangan',          'Dumingag'),
(187, 'New Basak',         'Dumingag'),
(188, 'Saad',              'Dumingag'),
(189, 'Salvador',          'Dumingag'),
(190, 'San Juan',          'Dumingag'),
(191, 'San Pablo (Pob.)',  'Dumingag'),
(192, 'San Pedro (Pob.)',  'Dumingag'),
(193, 'San Vicente',       'Dumingag'),
(194, 'Senote',            'Dumingag'),
(195, 'Sinonok',           'Dumingag'),
(196, 'Sunop',             'Dumingag'),
(197, 'Tagun',             'Dumingag'),
(198, 'Tamurayan',         'Dumingag'),
(199, 'Upper Landing',     'Dumingag'),
(200, 'Upper Timonan',     'Dumingag'),
(201, 'Bagong Oroquieta',  'Guipos'),
(202, 'Baguitan',          'Guipos'),
(203, 'Balongating',       'Guipos'),
(204, 'Canunan',           'Guipos'),
(205, 'Dacsol',            'Guipos'),
(206, 'Dagohoy',           'Guipos'),
(207, 'Dalapang',          'Guipos'),
(208, 'Datagan',           'Guipos'),
(209, 'Guling',            'Guipos'),
(210, 'Katipunan',         'Guipos'),
(211, 'Lintum',            'Guipos'),
(212, 'Litan',             'Guipos'),
(213, 'Magting',           'Guipos'),
(214, 'Poblacion',         'Guipos'),
(215, 'Regla',             'Guipos'),
(216, 'Sikatuna',          'Guipos'),
(217, 'Singclot',          'Guipos'),
(218, 'Bogo Calabat',      'Josefina'),
(219, 'Dawa (Diwa)',       'Josefina'),
(220, 'Ebarle',            'Josefina'),
(221, 'Gumahan (Pob)',     'Josefina'),
(222, 'Leonardo',          'Josefina'),
(223, 'Litapan',           'Josefina'),
(224, 'Low Bagong Tudela', 'Josefina'),
(225, 'Mansanas',          'Josefina'),
(226, 'Moradji',           'Josefina'),
(227, 'Nemeño',            'Josefina'),
(228, 'Nopulan',           'Josefina'),
(229, 'Sebukang',          'Josefina'),
(230, 'Tagaytay Hill',     'Josefina'),
(231, 'Upp Bagong Tudela', 'Josefina'),
(232, 'Bogayo',            'Kumalarang'),
(233, 'Bolisong',          'Kumalarang'),
(234, 'Boyugan East',      'Kumalarang'),
(235, 'Boyugan West',      'Kumalarang'),
(236, 'Bualan',            'Kumalarang'),
(237, 'Diplo',             'Kumalarang'),
(238, 'Gawil',             'Kumalarang'),
(239, 'Gusom',             'Kumalarang'),
(240, 'Kitaan Dagat',      'Kumalarang'),
(241, 'Lantawan',          'Kumalarang'),
(242, 'Limamawan',         'Kumalarang'),
(243, 'Mahayahay',         'Kumalarang'),
(244, 'Pangi',             'Kumalarang'),
(245, 'Picanan',           'Kumalarang'),
(246, 'Poblacion',         'Kumalarang'),
(247, 'Salagmanok',        'Kumalarang'),
(248, 'Secade',            'Kumalarang'),
(249, 'Suminalum',         'Kumalarang'),
(250, 'Bagalupa',          'Labangan'),
(251, 'Balimbingan',       'Labangan'),
(252, 'Binayan',           'Labangan'),
(253, 'Bokong',            'Labangan'),
(254, 'Bulanit',           'Labangan'),
(255, 'Cogonan',           'Labangan'),
(256, 'Combo',             'Labangan'),
(257, 'Dalapang',          'Labangan'),
(258, 'Dimasangca',        'Labangan'),
(259, 'Dipaya',            'Labangan'),
(260, 'Langapod',          'Labangan'),
(261, 'Lantian',           'Labangan'),
(262, 'Lower Campo Islam', 'Labangan'),
(263, 'Lower Pulacan',     'Labangan'),
(264, 'Lower Sang-an',     'Labangan'),
(265, 'New Labangan',      'Labangan'),
(266, 'Noboran',           'Labangan'),
(267, 'Old Labangan',      'Labangan'),
(268, 'San Isidro',        'Labangan'),
(269, 'Santa Cruz',        'Labangan'),
(270, 'Tapodoc',           'Labangan'),
(271, 'Tawagan Norte',     'Labangan'),
(272, 'Upper Campo Islam', 'Labangan'),
(273, 'Upper Pulacan',     'Labangan'),
(274, 'Upper Sang-an',     'Labangan'),
(275, 'Bagong Kahayag',    'Lakewood'),
(276, 'Baking',            'Lakewood'),
(277, 'Biswangan',         'Lakewood'),
(278, 'Bululawan',         'Lakewood'),
(279, 'Dagum',             'Lakewood'),
(280, 'Gasa',              'Lakewood'),
(281, 'Gatub',             'Lakewood'),
(282, 'Lukuan',            'Lakewood'),
(283, 'Matalang',          'Lakewood'),
(284, 'Poblacion',         'Lakewood'),
(285, 'Sapang Pinoles',    'Lakewood'),
(286, 'Sebuguey',          'Lakewood'),
(287, 'Tiwales',           'Lakewood'),
(288, 'Tubod',             'Lakewood'),
(289, 'Bulawan',           'Lapuyan'),
(290, 'Carpoc',            'Lapuyan'),
(291, 'Danganan',          'Lapuyan'),
(292, 'Dansal',            'Lapuyan'),
(293, 'Dumara',            'Lapuyan'),
(294, 'Linok Madalum',     'Lapuyan'),
(295, 'Luanan',            'Lapuyan'),
(296, 'Lubusan',           'Lapuyan'),
(297, 'Mahalingeb',        'Lapuyan'),
(298, 'Mandeg',            'Lapuyan'),
(299, 'Maralag',           'Lapuyan'),
(300, 'Maruing',           'Lapuyan'),
(301, 'Molum',             'Lapuyan'),
(302, 'Pampang',           'Lapuyan'),
(303, 'Pantad',            'Lapuyan'),
(304, 'Pingalay',		   'Lapuyan'),
(305, 'Poblacion',		   'Lapuyan'),
(306, 'Salambuyan',	       'Lapuyan'),
(307, 'San Jose',          'Lapuyan'),
(308, 'Sayog',             'Lapuyan'),
(309, 'Tabon',             'Lapuyan'),
(310, 'Talabab',           'Lapuyan'),
(311, 'Tiguha',            'Lapuyan'),
(312, 'Tininghalang',      'Lapuyan'),
(313, 'Tipasan',           'Lapuyan'),
(314, 'Tugaya',            'Lapuyan'),
(315, 'Bag-ong Balamban',  'Mahayag'),
(316, 'Bag-ong Dalaguete', 'Mahayag'),
(317, 'Boniao',            'Mahayag'),
(318, 'Delusom',           'Mahayag'),
(319, 'Diwan',             'Mahayag'),
(320, 'Guripan',           'Mahayag'),
(321, 'Kaangayan',         'Mahayag'),
(322, 'Kabuhi',            'Mahayag'),
(323, 'Lourmah',           'Mahayag'),
(324, 'Lower Salug Daku',  'Mahayag'),
(325, 'Lower Santo Niño',  'Mahayag'),
(326, 'Malubo',            'Mahayag'),
(327, 'Manguiles',         'Mahayag'),
(328, 'Marabanan',         'Mahayag'),
(329, 'Panagaan',          'Mahayag'),
(330, 'Paraiso',           'Mahayag'),
(331, 'Pedagan',           'Mahayag'),
(332, 'Poblacion',         'Mahayag'),
(333, 'Pugwan',            'Mahayag'),
(334, 'San Isidro',        'Mahayag'),
(335, 'San Jose',          'Mahayag'),
(336, 'San Vicente',       'Mahayag'),
(337, 'Santa Cruz',        'Mahayag'),
(338, 'Sicpao',            'Mahayag'),
(339, 'Tuboran',           'Mahayag'),
(340, 'Tulan',             'Mahayag'),
(341, 'Tumapic',           'Mahayag'),
(342, 'Upper Salug Daku',  'Mahayag'),
(343, 'Upper Santo Niño',  'Mahayag'),
(344, 'Balintawak',        'Margosatubig'),
(345, 'Bularong',          'Margosatubig'),
(346, 'Digon',             'Margosatubig'),
(347, 'Guinimanan',        'Margosatubig'),
(348, 'Igat Island',       'Margosatubig'),
(349, 'Josefina',          'Margosatubig'),
(350, 'Kalian',            'Margosatubig'),
(351, 'Kolot',             'Margosatubig'),
(352, 'Limamawan',         'Margosatubig'),
(353, 'Limbatong',         'Margosatubig'),
(354, 'Lumbog',            'Margosatubig'),
(355, 'Magahis',           'Margosatubig'),
(356, 'Poblacion',         'Margosatubig'),
(357, 'Sagua',             'Margosatubig'),
(358, 'Talanusa',          'Margosatubig'),
(359, 'Tiguian',           'Margosatubig'),
(360, 'Tulapok',           'Margosatubig'),
(361, 'Bacahan',           'Midsalip'),
(362, 'Balonai',           'Midsalip'),
(363, 'Bibilop',           'Midsalip'),
(364, 'Buloron',           'Midsalip'),
(365, 'Cabaloran',         'Midsalip'),
(366, 'Canipay Norte',     'Midsalip'),
(367, 'Canipay Sur',       'Midsalip'),
(368, 'Cumarom',           'Midsalip'),
(369, 'Dakayakan',         'Midsalip'),
(370, 'Duelic',            'Midsalip'),
(371, 'Dumalinao',         'Midsalip'),
(372, 'Ecuan',             'Midsalip'),
(373, 'Golictop',          'Midsalip'),
(374, 'Guinabot',          'Midsalip'),
(375, 'Guitalos',          'Midsalip'),
(376, 'Guma',              'Midsalip'),
(377, 'Kahayagan',         'Midsalip'),
(378, 'Licuro-an',         'Midsalip'),
(379, 'Lumpunid',          'Midsalip'),
(380, 'Matalang',          'Midsalip'),
(381, 'New Katipunan',     'Midsalip'),
(382, 'New Unidos',        'Midsalip'),
(383, 'Palili',            'Midsalip'),
(384, 'Pawan',             'Midsalip'),
(385, 'Pili',              'Midsalip'),
(386, 'Pisompongan',       'Midsalip'),
(387, 'Piwan',             'Midsalip'),
(388, 'Poblacion A',       'Midsalip'),
(389, 'Poblacion B',       'Midsalip'),
(390, 'Sigapod',           'Midsalip'),
(391, 'Timbaboy',          'Midsalip'),
(392, 'Tulbong',           'Midsalip'),
(393, 'Tuluan',            'Midsalip'),
(394, 'Alicia',            'Molave'),
(395, 'Ariosa',            'Molave'),
(396, 'Bagong Argao',      'Molave'),
(397, 'Bagong Gutlang',    'Molave'),
(398, 'Blancia',           'Molave'),
(399, 'Bogo Capalaran',    'Molave'),
(400, 'Culo',              'Molave'),
(401, 'Dalaon',            'Molave'),
(402, 'Dipolo',            'Molave'),
(403, 'Dontulan',          'Molave'),
(404, 'Gonosan',           'Molave'),
(405, 'Lower Dimalinao',   'Molave'),
(406, 'Lower Dimorok',     'Molave'),
(407, 'Mabuhay',           'Molave'),
(408, 'Madasigon (Pob)',   'Molave'),
(409, 'Makugihon (Pob)',   'Molave'),
(410, 'Maloloy-on (Pob)',  'Molave'),
(411, 'Miligan',           'Molave'),
(412, 'Parasan',           'Molave'),
(413, 'Rizal',             'Molave'),
(414, 'Santo Rosario',     'Molave'),
(415, 'Silangit',          'Molave'),
(416, 'Simata',            'Molave'),
(417, 'Sudlon',            'Molave'),
(418, 'Upper Dimorok',     'Molave'),
(419, 'Alegria',           'Pagadian'),
(420, 'Balangasan',        'Pagadian'),
(421, 'Balintawak',        'Pagadian'),
(422, 'Baloyboan',         'Pagadian'),
(423, 'Banale',            'Pagadian'),
(424, 'Bogo',              'Pagadian'),
(425, 'Bomba',             'Pagadian'),
(426, 'Buenavista',        'Pagadian'),
(427, 'Bulatok',           'Pagadian'),
(428, 'Bulawan',           'Pagadian'),
(429, 'Dampalan',          'Pagadian'),
(430, 'Danlugan',          'Pagadian'),
(431, 'Dao',               'Pagadian'),
(432, 'Datagan',           'Pagadian'),
(433, 'Deborok',           'Pagadian'),
(434, 'Ditoray',           'Pagadian'),
(435, 'Dumagoc',           'Pagadian'),
(436, 'Gatas',             'Pagadian'),
(437, 'Gubac',             'Pagadian'),
(438, 'Gubang',            'Pagadian'),
(439, 'Kagawasan',         'Pagadian'),
(440, 'Kahayagan',         'Pagadian'),
(441, 'Kalasan',           'Pagadian'),
(442, 'Kawit',             'Pagadian'),
(443, 'La Suerte',         'Pagadian'),
(444, 'Lala',              'Pagadian'),
(445, 'Lapidian',          'Pagadian'),
(446, 'Lenienza',          'Pagadian'),
(447, 'Lison Valley',      'Pagadian'),
(448, 'Lourdes',           'Pagadian'),
(449, 'Lower Sibatang',    'Pagadian'),
(450, 'Lumad',             'Pagadian'),
(451, 'Lumbia',            'Pagadian'),
(452, 'Macasing',          'Pagadian'),
(453, 'Manga',             'Pagadian'),
(454, 'Muricay',           'Pagadian'),
(455, 'Napolan',           'Pagadian'),
(456, 'Palpalan',          'Pagadian'),
(457, 'Pedulonan',         'Pagadian'),
(458, 'Poloyagan',         'Pagadian'),
(459, 'San Francisco ',    'Pagadian'),
(460, 'San Jose ',         'Pagadian'),
(461, 'San Pedro',         'Pagadian'),
(462, 'Santa Lucia',       'Pagadian'),
(463, 'Santa Maria',       'Pagadian'),
(464, 'Santiago',          'Pagadian'),
(465, 'Santo Niño',        'Pagadian'),
(466, 'Tawagan Sur',       'Pagadian'),
(467, 'Tiguma',            'Pagadian'),
(468, 'Tuburan',           'Pagadian'),
(469, 'Tulangan',          'Pagadian'),
(470, 'Tulawas',           'Pagadian'),
(471, 'Upper Sibatang',    'Pagadian'),
(472, 'White Beach',       'Pagadian'),
(473, 'Balabawan',         'Pitogo'),
(474, 'Balong-balong',     'Pitogo'),
(475, 'Colojo',            'Pitogo'),
(476, 'Liasan',            'Pitogo'),
(477, 'Liguac',            'Pitogo'),
(478, 'Limbayan',          'Pitogo'),
(479, 'Lower Paniki-an',   'Pitogo'),
(480, 'Matin-ao',          'Pitogo'),
(481, 'Panubigan',         'Pitogo'),
(482, 'Poblacion',         'Pitogo'),
(483, 'Punta Flecha',      'Pitogo'),
(484, 'San Isidro',        'Pitogo'),
(485, 'Sugbay Dos',        'Pitogo'),
(486, 'Tongao',            'Pitogo'),
(487, 'Upper Paniki-an',   'Pitogo'),
(488, 'Bag-ong Opon',      'Ramon Magsaysay'),
(489, 'Bambong Daku',      'Ramon Magsaysay'),
(490, 'Bambong Diut',      'Ramon Magsaysay'),
(491, 'Bobongan',          'Ramon Magsaysay'),
(492, 'Campo IV',          'Ramon Magsaysay'),
(493, 'Campo V',           'Ramon Magsaysay'),
(494, 'Caniangan',         'Ramon Magsaysay'),
(495, 'Dipalusan',         'Ramon Magsaysay'),
(496, 'Eastern Bobongan',  'Ramon Magsaysay'),
(497, 'Esperanza',         'Ramon Magsaysay'),
(498, 'Gapasan',           'Ramon Magsaysay'),
(499, 'Katipunan',         'Ramon Magsaysay'),
(500, 'Kauswagan',         'Ramon Magsaysay'),
(501, 'Lower Sambulawan',  'Ramon Magsaysay'),
(502, 'Mabini',            'Ramon Magsaysay'),
(503, 'Magsaysay',         'Ramon Magsaysay'),
(504, 'Malating',          'Ramon Magsaysay'),
(505, 'Paradise',          'Ramon Magsaysay'),
(506, 'Pasingkalan',       'Ramon Magsaysay'),
(507, 'Poblacion',         'Ramon Magsaysay'),
(508, 'San Fernando',      'Ramon Magsaysay'),
(509, 'Santo Rosario',     'Ramon Magsaysay'),
(510, 'Sapa Anding',       'Ramon Magsaysay'),
(511, 'Sinaguing',         'Ramon Magsaysay'),
(512, 'Switch',            'Ramon Magsaysay'),
(513, 'Upper Laperian',    'Ramon Magsaysay'),
(514, 'Wakat',             'Ramon Magsaysay'),
(515, 'Betinan',           'San Miguel'),
(516, 'Bulawan',           'San Miguel'),
(517, 'Calube',            'San Miguel'),
(518, 'Concepcion',        'San Miguel'),
(519, 'Dao-an',            'San Miguel'),
(520, 'Dumalian',          'San Miguel'),
(521, 'Fatima',            'San Miguel'),
(522, 'Langilan',          'San Miguel'),
(523, 'Lantawan',          'San Miguel'),
(524, 'Laperian',          'San Miguel'),
(525, 'Libuganan',         'San Miguel'),
(526, 'Limonan',           'San Miguel'),
(527, 'Mati',              'San Miguel'),
(528, 'Ocapan',            'San Miguel'),
(529, 'Poblacion',         'San Miguel'),
(530, 'San Isidro',        'San Miguel'),
(531, 'Sayog',             'San Miguel'),
(532, 'Tapian',            'San Miguel'),
(533, 'Bag-ong Misamis',   'San Pablo'),
(534, 'Bubual',            'San Pablo'),
(535, 'Buton',             'San Pablo'),
(536, 'Culasian',          'San Pablo'),
(537, 'Daplayan',          'San Pablo'),
(538, 'Kalilangan',        'San Pablo'),
(539, 'Kapamanok',         'San Pablo'),
(540, 'Kondum',            'San Pablo'),
(541, 'Lumbayao',          'San Pablo'),
(542, 'Mabuhay',           'San Pablo'),
(543, 'Marcos Village',    'San Pablo'),
(544, 'Miasin',            'San Pablo'),
(545, 'Mulansong',         'San Pablo'),
(546, 'Pantad',            'San Pablo'),
(547, 'Pao',               'San Pablo'),
(548, 'Payag',             'San Pablo'),
(549, 'Poblacion',         'San Pablo'),
(550, 'Pongapong',         'San Pablo'),
(551, 'Sacbulan',          'San Pablo'),
(552, 'Sagasan',           'San Pablo'),
(553, 'San Juan',          'San Pablo'),
(554, 'Senior',            'San Pablo'),
(555, 'Songgoy',           'San Pablo'),
(556, 'Tandubuay',         'San Pablo'),
(557, 'Teniapan',          'San Pablo'),
(558, 'Ticala Island',     'San Pablo'),
(559, 'Tubo-pait',         'San Pablo'),
(560, 'Villakapa',         'San Pablo'),
(561, 'Bag-ong Baroy',     'Sominot'),
(562, 'New Oroquieta',     'Sominot'),
(563, 'Barubuhan',         'Sominot'),
(564, 'Bulanay',           'Sominot'),
(565, 'Datagan',           'Sominot'),
(566, 'Eastern Poblacion', 'Sominot'),
(567, 'Lantawan',          'Sominot'),
(568, 'Libertad',          'Sominot'),
(569, 'Lumangoy',          'Sominot'),
(570, 'New Carmen',        'Sominot'),
(571, 'Picturan',          'Sominot'),
(572, 'Poblacion',         'Sominot'),
(573, 'Rizal',             'Sominot'),
(574, 'San Miguel',        'Sominot'),
(575, 'Santo Niño',        'Sominot'),
(576, 'Sawa',              'Sominot'),
(577, 'Tungawan',          'Sominot'),
(578, 'Upper Sicpao',      'Sominot'),
(579, 'Abong-abong',       'Tabina'),
(580, 'Baganian',          'Tabina'),
(581, 'Baya-baya',         'Tabina'),
(582, 'Capisan',           'Tabina'),
(583, 'Concepcion',        'Tabina'),
(584, 'Culabay',           'Tabina'),
(585, 'Doña Josefina',     'Tabina'),
(586, 'Lumbia',            'Tabina'),
(587, 'Mabuhay',           'Tabina'),
(588, 'Malim',             'Tabina'),
(589, 'Manicaan',          'Tabina'),
(590, 'New Oroquieta',     'Tabina'),
(591, 'Poblacion',         'Tabina'),
(592, 'San Francisco',     'Tabina'),
(593, 'Tultolan',          'Tabina'),
(594, 'Alang-alang',       'Tambulig'),
(595, 'Angeles',           'Tambulig'),
(596, 'Bag-ong Kauswagan', 'Tambulig'),
(597, 'Bag-ong Tabogon',   'Tambulig'),
(598, 'Balugo',            'Tambulig'),
(599, 'Cabgan',            'Tambulig'),
(600, 'Calolot',           'Tambulig'),
(601, 'Dimalinao',         'Tambulig'),
(602, 'Fabian (Balucot)',  'Tambulig'),
(603, 'Gabunon',           'Tambulig'),
(604, 'Happy Valley (Pob)','Tambulig'),
(605, 'Kapalaran',         'Tambulig'),
(606, 'Libato',            'Tambulig'),
(607, 'Limamaan',          'Tambulig'),
(608, 'Lower Liason',      'Tambulig'),
(609, 'Lower Lodiong',     'Tambulig'),
(610, 'Lower Tiparak',     'Tambulig'),
(611, 'Lower Usogan',      'Tambulig'),
(612, 'Maya-maya',         'Tambulig'),
(613, 'New Village (Pob)', 'Tambulig'),
(614, 'Pelocuban',         'Tambulig'),
(615, 'Riverside (Pob)',   'Tambulig'),
(616, 'Sagrada Familia',   'Tambulig'),
(617, 'San Jose',          'Tambulig'),
(618, 'San Vicente',       'Tambulig'),
(619, 'Sumalig',           'Tambulig'),
(620, 'Tuluan',            'Tambulig'),
(621, 'Tungawan',          'Tambulig'),
(622, 'Upper Liaison',     'Tambulig'),
(623, 'Upper Lodiong',     'Tambulig'),
(624, 'Upper Tiparak',     'Tambulig'),
(625, 'Begong',            'Tigbao'),
(626, 'Busol',             'Tigbao'),
(627, 'Caluma',            'Tigbao'),
(628, 'Diana Countryside', 'Tigbao'),
(629, 'Guinlin',           'Tigbao'),
(630, 'Lacarayan',         'Tigbao'),
(631, 'Lacupayan',         'Tigbao'),
(632, 'Lebayoy',           'Tigbao'),
(633, 'Limas',             'Tigbao'),
(634, 'Longmot',           'Tigbao'),
(635, 'Maragang',          'Tigbao'),
(636, 'Mate',              'Tigbao'),
(637, 'Nangan-nangan',     'Tigbao'),
(638, 'New Tuburan',       'Tigbao'),
(639, 'Nilo',              'Tigbao'),
(640, 'Tigbao',            'Tigbao'),
(641, 'Timolan',           'Tigbao'),
(642, 'Upper Nilo',        'Tigbao'),
(643, 'Alindahaw',         'Tukuran'),
(644, 'Baclay',            'Tukuran'),
(645, 'Balimbingan',       'Tukuran'),
(646, 'Buenasuerte',       'Tukuran'),
(647, 'Camanga',           'Tukuran'),
(648, 'Curvada',           'Tukuran'),
(649, 'Laperian',          'Tukuran'),
(650, 'Libertad',          'Tukuran'),
(651, 'Lower Bayao',       'Tukuran'),
(652, 'Luy-a',             'Tukuran'),
(653, 'Manilan',           'Tukuran'),
(654, 'Manlayag',          'Tukuran'),
(655, 'Militar',           'Tukuran'),
(656, 'Navalan',           'Tukuran'),
(657, 'Panduma Senior',    'Tukuran'),
(658, 'Sambulawan',        'Tukuran'),
(659, 'San Antonio',       'Tukuran'),
(660, 'San Carlos (Pob)',  'Tukuran'),
(661, 'Santo Niño (Pob)',  'Tukuran'),
(662, 'Santo Rosario',     'Tukuran'),
(663, 'Sugod',             'Tukuran'),
(664, 'Tabuan',            'Tukuran'),
(665, 'Tagulo',            'Tukuran'),
(666, 'Tinotungan',        'Tukuran'),
(667, 'Upper Bayao',       'Tukuran'),
(668, 'Ambulon',           'Vincenzo Sagun'),
(669, 'Biu-os',            'Vincenzo Sagun'),
(670, 'Cogon',             'Vincenzo Sagun'),
(671, 'Danan',             'Vincenzo Sagun'),
(672, 'Kabatan (Pob)',     'Vincenzo Sagun'),
(673, 'Kapatagan',         'Vincenzo Sagun'),
(674, 'Limason',           'Vincenzo Sagun'),
(675, 'Linoguayan',        'Vincenzo Sagun'),
(676, 'Lumbal',            'Vincenzo Sagun'),
(677, 'Lunib',             'Vincenzo Sagun'),
(678, 'Maculay',           'Vincenzo Sagun'),
(679, 'Maraya',            'Vincenzo Sagun'),
(680, 'Sagucan',           'Vincenzo Sagun'),
(681, 'Walingwaling',      'Vincenzo Sagun');
